services:
  noded:
    build: .
    ports:
      - "6001:8000"
    container_name: noded-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/app/dist:ro
      - ./index.html:/app/index.html:ro
      - ./standalone.html:/app/standalone.html:ro